package retailer;


/**
* retailer/_RetailerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 11:04:37 o'clock PM EDT
*/

public class _RetailerStub extends org.omg.CORBA.portable.ObjectImpl implements retailer.Retailer
{

  public tools.Item[] getCatalog (int customerReferenceNumber)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCatalog", true);
                $out.write_long (customerReferenceNumber);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCatalog (customerReferenceNumber        );
            } finally {
                _releaseReply ($in);
            }
  } // getCatalog

  public tools.ItemShippingStatus[] submitOrder (int customerReferenceNumber, tools.Item[] itemList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("submitOrder", true);
                $out.write_long (customerReferenceNumber);
                tools.ItemListHelper.write ($out, itemList);
                $in = _invoke ($out);
                tools.ItemShippingStatus $result[] = tools.ItemShippingStatusListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return submitOrder (customerReferenceNumber, itemList        );
            } finally {
                _releaseReply ($in);
            }
  } // submitOrder

  public tools.SignUpResult signUp (String name, String password, String street1, String street2, String city, String state, String zip, String country)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("signUp", true);
                $out.write_string (name);
                $out.write_string (password);
                $out.write_string (street1);
                $out.write_string (street2);
                $out.write_string (city);
                $out.write_string (state);
                $out.write_string (zip);
                $out.write_string (country);
                $in = _invoke ($out);
                tools.SignUpResult $result = tools.SignUpResultHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return signUp (name, password, street1, street2, city, state, zip, country        );
            } finally {
                _releaseReply ($in);
            }
  } // signUp

  public tools.Customer signIn (int customerReferenceNumber, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("signIn", true);
                $out.write_long (customerReferenceNumber);
                $out.write_string (password);
                $in = _invoke ($out);
                tools.Customer $result = tools.CustomerHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return signIn (customerReferenceNumber, password        );
            } finally {
                _releaseReply ($in);
            }
  } // signIn

  public tools.Item[] getProducts (String productID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProducts", true);
                $out.write_string (productID);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProducts (productID        );
            } finally {
                _releaseReply ($in);
            }
  } // getProducts

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:retailer/Retailer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RetailerStub
