package retailer;


/**
* retailer/RetailerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 10:55:15 AM EDT
*/

abstract public class RetailerHelper
{
  private static String  _id = "IDL:retailer/Retailer:1.0";

  public static void insert (org.omg.CORBA.Any a, retailer.Retailer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static retailer.Retailer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (retailer.RetailerHelper.id (), "Retailer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static retailer.Retailer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RetailerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, retailer.Retailer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static retailer.Retailer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof retailer.Retailer)
      return (retailer.Retailer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      retailer._RetailerStub stub = new retailer._RetailerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static retailer.Retailer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof retailer.Retailer)
      return (retailer.Retailer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      retailer._RetailerStub stub = new retailer._RetailerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
