package retailer;


/**
* retailer/RetailerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 11:04:37 o'clock PM EDT
*/

public interface RetailerOperations 
{
  tools.Item[] getCatalog (int customerReferenceNumber);
  tools.ItemShippingStatus[] submitOrder (int customerReferenceNumber, tools.Item[] itemList);
  tools.SignUpResult signUp (String name, String password, String street1, String street2, String city, String state, String zip, String country);
  tools.Customer signIn (int customerReferenceNumber, String password);
  tools.Item[] getProducts (String productID);
  void shutdown ();
} // interface RetailerOperations
