package warehouse;


/**
* warehouse/_WarehouseStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Monday, June 22, 2015 10:15:34 o'clock PM EDT
*/

public class _WarehouseStub extends org.omg.CORBA.portable.ObjectImpl implements warehouse.Warehouse
{

  public tools.Item[] getProductsByID (int productID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProductsByID", true);
                $out.write_long (productID);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProductsByID (productID        );
            } finally {
                _releaseReply ($in);
            }
  } // getProductsByID


  // get the specific product by id, if null/empty, all returned
  public tools.Item[] getProductsByType (String productType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProductsByType", true);
                $out.write_string (productType);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProductsByType (productType        );
            } finally {
                _releaseReply ($in);
            }
  } // getProductsByType


  // get a list of products by product type, if null/mpty,all returned
  public tools.Item[] getProductsByRegisteredManufacturers (String manufacturerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProductsByRegisteredManufacturers", true);
                $out.write_string (manufacturerName);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProductsByRegisteredManufacturers (manufacturerName        );
            } finally {
                _releaseReply ($in);
            }
  } // getProductsByRegisteredManufacturers


  //get a list of products by manufacturer name,if null/empty, all returned
  public tools.Item[] getProducts (int productID, String manufacturerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getProducts", true);
                $out.write_long (productID);
                $out.write_string (manufacturerName);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getProducts (productID, manufacturerName        );
            } finally {
                _releaseReply ($in);
            }
  } // getProducts

  public boolean registerRetailer (String retailerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerRetailer", true);
                $out.write_string (retailerName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerRetailer (retailerName        );
            } finally {
                _releaseReply ($in);
            }
  } // registerRetailer

  public boolean unregisterRegailer (String retailerName)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregisterRegailer", true);
                $out.write_string (retailerName);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return unregisterRegailer (retailerName        );
            } finally {
                _releaseReply ($in);
            }
  } // unregisterRegailer

  public tools.Item[] shippingGoods (tools.Item[] itemList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shippingGoods", true);
                tools.ItemListHelper.write ($out, itemList);
                $in = _invoke ($out);
                tools.Item $result[] = tools.ItemListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return shippingGoods (itemList        );
            } finally {
                _releaseReply ($in);
            }
  } // shippingGoods

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:warehouse/Warehouse:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _WarehouseStub
