package warehouse;


/**
* warehouse/WarehouseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 11:04:37 o'clock PM EDT
*/

abstract public class WarehouseHelper
{
  private static String  _id = "IDL:warehouse/Warehouse:1.0";

  public static void insert (org.omg.CORBA.Any a, warehouse.Warehouse that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static warehouse.Warehouse extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (warehouse.WarehouseHelper.id (), "Warehouse");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static warehouse.Warehouse read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WarehouseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, warehouse.Warehouse value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static warehouse.Warehouse narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof warehouse.Warehouse)
      return (warehouse.Warehouse)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      warehouse._WarehouseStub stub = new warehouse._WarehouseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static warehouse.Warehouse unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof warehouse.Warehouse)
      return (warehouse.Warehouse)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      warehouse._WarehouseStub stub = new warehouse._WarehouseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
