package warehouse;


/**
* warehouse/Warehouse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 1:39:40 o'clock PM EDT
*/

public interface Warehouse extends WarehouseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Warehouse
