package manufacturer;


/**
* manufacturer/ManufacturerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Thursday, June 18, 2015 6:22:17 o'clock PM EDT
*/

public interface ManufacturerOperations 
{
  String processPurchaseOrder (tools.Item item);
  tools.Product getProductInfo (String aProdName);
  boolean receivePayment (String orderNum, float totalPrice);
  tools.Product[] getProductList ();
} // interface ManufacturerOperations
