package manufacturer;


/**
* manufacturer/ManufacturerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Tuesday, June 23, 2015 11:24:18 o'clock AM EDT
*/

public interface ManufacturerOperations 
{
  String processPurchaseOrder (tools.Item item);
  tools.Product getProductInfo (String aProdName);
  boolean receivePayment (String orderNum, float totalPrice);
  tools.Product[] getProductList ();
  void shutdown ();
} // interface ManufacturerOperations
