package tools;

/**
* tools/ItemShippingStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Wednesday, June 24, 2015 9:54:14 PM EDT
*/

public final class ItemShippingStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public tools.ItemShippingStatus value = null;

  public ItemShippingStatusHolder ()
  {
  }

  public ItemShippingStatusHolder (tools.ItemShippingStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tools.ItemShippingStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tools.ItemShippingStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ItemShippingStatusHelper.type ();
  }

}
