package tools;


/**
* tools/ItemShippingStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Thursday, June 18, 2015 6:22:17 o'clock PM EDT
*/

public abstract class ItemShippingStatus extends tools.Item
{
  protected boolean shippingStatus = false;

  private static String[] _truncatable_ids = {
    tools.ItemShippingStatusHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.shippingStatus = istream.read_boolean ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    ostream.write_boolean (this.shippingStatus);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ItemShippingStatusHelper.type ();
  }
} // class ItemShippingStatus
