package tools;


/**
* tools/ItemShippingStatusDefaultFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Tuesday, June 23, 2015 11:24:18 o'clock AM EDT
*/

public class ItemShippingStatusDefaultFactory implements org.omg.CORBA.portable.ValueFactory {

  public java.io.Serializable read_value (org.omg.CORBA_2_3.portable.InputStream is)
  {
    return is.read_value(new ItemShippingStatusImpl ());
  }
}
