package tools;


/**
* tools/ItemListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Tuesday, June 23, 2015 11:24:18 o'clock AM EDT
*/

public final class ItemListHolder implements org.omg.CORBA.portable.Streamable
{
  public tools.Item value[] = null;

  public ItemListHolder ()
  {
  }

  public ItemListHolder (tools.Item[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tools.ItemListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tools.ItemListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ItemListHelper.type ();
  }

}
