package tools;


/**
* tools/Item.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Thursday, June 18, 2015 6:22:17 o'clock PM EDT
*/

public abstract class Item extends tools.Product
{
  protected int quantity = (int)0;

  private static String[] _truncatable_ids = {
    tools.ItemHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public abstract int getQuantity ();

  public abstract void setQuantity (int q);

  public abstract tools.Product cloneProduct ();

  public abstract boolean isSameProductAs (tools.Item otherItem);

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    super._read (istream);
    this.quantity = istream.read_long ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    super._write (ostream);
    ostream.write_long (this.quantity);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ItemHelper.type ();
  }
} // class Item
