package tools;


/**
* tools/ItemShippingStatusListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Thursday, June 18, 2015 6:22:17 o'clock PM EDT
*/

public final class ItemShippingStatusListHolder implements org.omg.CORBA.portable.Streamable
{
  public tools.ItemShippingStatus value[] = null;

  public ItemShippingStatusListHolder ()
  {
  }

  public ItemShippingStatusListHolder (tools.ItemShippingStatus[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tools.ItemShippingStatusListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tools.ItemShippingStatusListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ItemShippingStatusListHelper.type ();
  }

}
