package tools;

/**
* tools/ProductHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 11:04:37 o'clock PM EDT
*/

public final class ProductHolder implements org.omg.CORBA.portable.Streamable
{
  public tools.Product value = null;

  public ProductHolder ()
  {
  }

  public ProductHolder (tools.Product initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tools.ProductHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tools.ProductHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.ProductHelper.type ();
  }

}
