package tools;


/**
* tools/SignUpResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 10:55:15 AM EDT
*/

public abstract class SignUpResult implements org.omg.CORBA.portable.StreamableValue
{
  public boolean result = false;
  public int customerReferenceNumber = (int)0;
  public String message = null;

  private static String[] _truncatable_ids = {
    tools.SignUpResultHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    this.result = istream.read_boolean ();
    this.customerReferenceNumber = istream.read_long ();
    this.message = istream.read_string ();
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_boolean (this.result);
    ostream.write_long (this.customerReferenceNumber);
    ostream.write_string (this.message);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.SignUpResultHelper.type ();
  }
} // class SignUpResult
