package tools;

/**
* tools/SignUpResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from supplyChain.idl
* Sunday, June 21, 2015 1:39:40 o'clock PM EDT
*/

public final class SignUpResultHolder implements org.omg.CORBA.portable.Streamable
{
  public tools.SignUpResult value = null;

  public SignUpResultHolder ()
  {
  }

  public SignUpResultHolder (tools.SignUpResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tools.SignUpResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tools.SignUpResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tools.SignUpResultHelper.type ();
  }

}
